---
micronaut:
    application:
        name: producer-app
netty:
  default:
    allocator:
      max-order: 3
jackson:
    serialization:
        writeDatesAsTimestamps: false
---
#rabbitmq:
#    uri: amqp://localhost:5672
